import { useState, type FormEvent } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { ArrowDown, ArrowRight, ArrowUpRight, BadgeCheck, Building2, CheckCheck, ChevronDown, CircleCheck, Clock3, Handshake, LandPlot, LockKeyhole, MapPin, Search, ShieldCheck, Store, TrendingUp, Warehouse } from 'lucide-react'
import { getProperties } from '../api/properties'
import { isDemo } from '../api/http'
import { photos } from '../data/mock'
import { cities, propertyTypes } from '../lib/format'
import { useResource } from '../hooks/useResource'
import { ErrorState, LoadingCards, EmptyState } from '../components/ui'
import { PropertyCard } from '../components/PropertyCard'

const categoryIcons = [Building2, Store, Warehouse, LandPlot, Building2]
export default function HomePage() {
  const navigate = useNavigate()
  const [listingType, setListingType] = useState('sale')
  const properties = useResource((signal) => getProperties({ per_page: 3 }, signal), 'featured')
  const search = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const data = new FormData(event.currentTarget)
    const params = new URLSearchParams({ listing_type: listingType })
    for (const key of ['city', 'property_type', 'price_max']) if (data.get(key)) params.set(key, String(data.get(key)))
    navigate(`/properties?${params}`)
  }
  return <>
    <section className="hero"><img src={photos.tower} alt="Contemporary glass commercial towers reaching into the sky" className="hero-image" fetchPriority="high" /><div className="hero-overlay" /><div className="container hero-content"><div className="hero-eyebrow"><span /> SPACE FOR YOUR NEXT CHAPTER</div><h1>Find the Right Space<br />for Your <em>Business.</em></h1><p className="hero-description">Prime commercial properties. Trusted professionals.<br className="hidden sm:block" /> Real opportunities.</p><div className="search-block"><div className="search-tabs" aria-label="Search listing type">{[['sale', 'Buy a property'], ['lease', 'Rent a space']].map(([value, label]) => <button type="button" key={value} aria-pressed={listingType === value} className={listingType === value ? 'active' : ''} onClick={() => setListingType(value)}>{label}</button>)}</div><form onSubmit={search} className="hero-search"><label><span><MapPin size={14} /> LOCATION</span><div className="select-wrap"><select name="city" aria-label="Search location"><option value="">Where would you like to grow?</option>{cities.map((city) => <option key={city}>{city}</option>)}</select><ChevronDown size={16} /></div></label><label><span><Building2 size={14} /> PROPERTY TYPE</span><div className="select-wrap"><select name="property_type" aria-label="Search property type"><option value="">All property types</option>{propertyTypes.map((type) => <option key={type}>{type}</option>)}</select><ChevronDown size={16} /></div></label><label><span>₱ &nbsp; PRICE RANGE</span><div className="select-wrap"><select name="price_max" aria-label="Search price range"><option value="">Any price</option>{(listingType === 'lease' ? [150000, 300000, 500000, 1000000] : [50000000, 100000000, 200000000]).map((price) => <option key={price} value={price}>Up to ₱{price.toLocaleString()}</option>)}</select><ChevronDown size={16} /></div></label><button className="btn hero-search-button" type="submit"><Search size={19} /> Search</button></form></div><div className="hero-bottom"><p>YOUR AMBITION. THE RIGHT ADDRESS.</p><Link to="/#featured" aria-label="Explore featured properties"><ArrowDown size={18} /></Link></div></div><span className="hero-caption">A new perspective on commercial real estate.</span></section>
    <section className="trust-strip"><div className="container grid grid-cols-2 lg:grid-cols-4">{[[ShieldCheck, 'Verified Listings', 'Clarity in every detail'], [BadgeCheck, 'Trusted Brokers', 'People behind every property'], [Clock3, 'Fast Response Time', 'A direct line to your broker'], [LockKeyhole, 'Secure Transactions', 'Start with private inquiries']].map(([Icon, title, text]) => { const Component = Icon as typeof ShieldCheck; return <div className="trust-item" key={String(title)}><Component size={25} strokeWidth={1.3} /><div><h2>{String(title)}</h2><p>{String(text)}</p></div></div> })}</div></section>
    <section className="container section-space" id="property-types"><div className="section-heading"><div><p className="eyebrow text-clay">A SPACE FOR EVERY AMBITION</p><h2>What's your next move?</h2></div><p className="section-description">From your first storefront to your next headquarters,<br className="hidden md:block" /> find a space that works as hard as you do.</p></div><div className="category-grid">{propertyTypes.map((type, index) => { const Icon = categoryIcons[index]; return <Link key={type} to={`/properties?property_type=${encodeURIComponent(type)}`} className="category-card"><Icon size={29} strokeWidth={1.1} /><span>{type}</span><ArrowUpRight size={16} /></Link> })}</div></section>
    <section className="featured-section section-space" id="featured"><div className="container"><div className="section-heading"><div><p className="eyebrow text-clay">THE PROPERTY COLLECTION</p><h2>Spaces with possibility.</h2></div><Link className="text-link" to="/properties">Explore all properties <ArrowUpRight size={19} /></Link></div>{isDemo && <p className="collection-note">Preview collection · sample properties for exploration</p>}{properties.loading ? <LoadingCards /> : properties.error ? <ErrorState error={properties.error} retry={properties.retry} /> : properties.data?.data.length ? <div className="grid gap-7 md:grid-cols-2 xl:grid-cols-3">{properties.data.data.map((property) => <PropertyCard key={property.id} property={property} />)}</div> : <EmptyState title="New opportunities are on the way." description="Our property collection will appear here as brokers publish available spaces." />}</div></section>
    <section className="container section-space" id="about"><div className="why-layout"><div><p className="eyebrow text-clay">THE ESTATEHUB APPROACH</p><h2 className="editorial-heading">More than a space.<br />A step <em>forward.</em></h2><p className="text-muted leading-8 mt-6 max-w-md">The right property is the beginning of something bigger. We bring the details, the professionals, and the possibilities together, so you can focus on your business.</p><Link className="text-link mt-8" to="/properties">Find your next opportunity <ArrowRight size={18} /></Link></div><div className="grid gap-x-8 gap-y-10 sm:grid-cols-2">{[[CircleCheck, 'Verified Listings', 'Know the space before you make a move. Clear property details and a broker you can reach.'], [Handshake, 'Trusted Brokers', 'Work directly with professionals who understand your business and your next step.'], [CheckCheck, 'Easy Inquiries', 'Ask a question, arrange a viewing, and keep every conversation in one place.'], [TrendingUp, 'Business Growth', 'Explore locations and spaces that give your next chapter room to grow.']].map(([Icon, title, text]) => { const Component = Icon as typeof CircleCheck; return <article key={String(title)} className="why-card"><Component size={25} strokeWidth={1.3} /><h3>{String(title)}</h3><p>{String(text)}</p></article> })}</div></div></section>
    <section className="container pb-20" id="brokers"><div className="broker-banner"><div><p className="eyebrow text-white/60">GOOD SPACES. GOOD PEOPLE.</p><h2>Your next move starts<br />with a conversation.</h2><p>Find a property. Meet its broker. See what's possible.</p></div><Link className="btn btn-light" to="/properties">Find your space <ArrowUpRight size={19} /></Link></div></section>
  </>
}
