import { useState, type FormEvent } from 'react'
import { Link, useLocation } from 'react-router-dom'
import { ArrowUpRight, BadgeCheck, Building2, CarFront, Check, ChevronLeft, ChevronRight, Expand, KeyRound, LockKeyhole, MapPin, MessageSquare, MoveUpRight, Ruler, ShieldCheck, Accessibility } from 'lucide-react'
import type { Property } from '../domain/types'
import { ApiError, isDemo } from '../api/http'
import { submitInquiry } from '../api/client'
import { useMarketplace } from '../context/MarketplaceContext'
import { formatNumber, formatPrice, typeLabel } from '../lib/format'
import { Modal, PropertyImage } from './ui'
import { SaveButton } from './PropertyCard'

export function PropertyGallery({ property }: { property: Property }) {
  const [index, setIndex] = useState(0)
  const [fullscreen, setFullscreen] = useState(false)
  const images = property.images || []
  const change = (direction: number) => setIndex((index + direction + images.length) % images.length)
  return <><div className="property-gallery"><div className="gallery-main"><PropertyImage src={images[index]?.url} alt={`${property.title}, image ${index + 1}`} eager className="w-full h-full object-cover" />{images.length > 0 && <button className="gallery-expand" onClick={() => setFullscreen(true)}><Expand size={16} /> View photos <span>{index + 1}/{images.length}</span></button>}</div>{images.length > 1 && <div className="gallery-thumbnails">{images.map((image, position) => <button key={image.id} onClick={() => setIndex(position)} aria-label={`View property image ${position + 1}`} aria-pressed={index === position} className={index === position ? 'active' : ''}><PropertyImage src={image.url} alt={`${property.title} photo ${position + 1}`} className="h-full w-full object-cover" /></button>)}</div>}</div>{fullscreen && <Modal title={`${property.title} · ${index + 1} / ${images.length}`} wide onClose={() => setFullscreen(false)}><div onKeyDown={(event) => { if (event.key === 'ArrowLeft') change(-1); if (event.key === 'ArrowRight') change(1) }}><PropertyImage src={images[index]?.url} alt={`${property.title}, fullscreen image ${index + 1}`} className="fullscreen-image" /><div className="flex justify-between mt-5"><button className="btn-quiet" onClick={() => change(-1)} aria-label="Previous fullscreen image"><ChevronLeft /> Previous</button><button className="btn-quiet" onClick={() => change(1)} aria-label="Next fullscreen image">Next <ChevronRight /></button></div></div></Modal>}</>
}
export function PropertyInfo({ property }: { property: Property }) {
  return <><div className="flex flex-wrap items-center gap-3 mb-5"><span className="pill">{property.listing_type === 'lease' ? 'For Rent' : 'For Sale'}</span><span className="text-xs text-muted">PROPERTY REF. MR-{String(property.id).padStart(4, '0')}</span></div><h1 className="detail-title">{property.title}</h1><p className="mt-4 flex items-center gap-2 text-muted"><MapPin size={17} />{property.location}</p><div className="detail-facts">{[[Ruler, formatNumber(property.floor_area) + ' m²', 'Floor area'], [Building2, typeLabel(property.property_type), 'Property type'], [KeyRound, property.listing_type === 'lease' ? 'For Rent' : 'For Sale', 'Listing type'], [Check, typeLabel(property.status), 'Availability']].map(([Icon, value, label]) => { const Component = Icon as typeof Ruler; return <div key={String(label)}><Component size={20} strokeWidth={1.4} /><strong>{String(value)}</strong><span>{String(label)}</span></div> })}</div><section className="detail-section"><p className="eyebrow text-clay">THE OPPORTUNITY</p><h2>Room to make it your own.</h2><p className="whitespace-pre-line text-muted leading-8 mt-5">{property.description || 'Contact the listing broker for the full property overview and current terms.'}</p></section></>
}
const featureIcons: Record<string, typeof CarFront> = { Parking: CarFront, Security: ShieldCheck, Accessibility, 'Business District': Building2, 'Ready Occupancy': KeyRound }
export function FeatureList({ features }: { features?: string[] }) {
  return <section className="detail-section"><h2>Property features</h2>{features?.length ? <div className="grid grid-cols-2 sm:grid-cols-3 gap-5 mt-6">{features.map((feature) => { const Icon = featureIcons[feature] || Check; return <div key={feature} className="feature-item"><Icon size={19} strokeWidth={1.4} /><span>{feature}</span></div> })}</div> : <p className="mt-4 text-muted text-sm leading-7">Amenities have not been provided for this listing. Ask the broker about parking, accessibility, security, and occupancy before arranging a viewing.</p>}</section>
}
export function InquiryButton({ property, initialOpen = false }: { property: Property; initialOpen?: boolean }) {
  const [open, setOpen] = useState(initialOpen)
  const [message, setMessage] = useState(`Hi, I’m interested in ${property.title}. Could you share more details and viewing availability?`)
  const [sending, setSending] = useState(false)
  const [success, setSuccess] = useState(false)
  const [error, setError] = useState('')
  const { user, refresh } = useMarketplace()
  const location = useLocation()
  const send = async (event: FormEvent) => {
    event.preventDefault()
    if (sending) return
    if (message.trim().length < 10 || message.length > 2000) { setError('Please write a message between 10 and 2,000 characters.'); return }
    setSending(true); setError('')
    try { await submitInquiry(property.id, message.trim()); setSuccess(true); refresh() }
    catch (error) { setError(error instanceof ApiError && error.status === 401 ? 'Your session expired. Please sign in again.' : error instanceof ApiError && error.status === 403 ? 'Please verify your email and ensure your client account is approved.' : error instanceof Error ? error.message : 'Please try again.') }
    finally { setSending(false) }
  }
  return <><button className="btn w-full" onClick={() => setOpen(true)}><MessageSquare size={18} /> Send Inquiry <ArrowUpRight size={17} /></button><button className="btn btn-outline w-full mt-3" onClick={() => setOpen(true)}>Contact Broker <MoveUpRight size={16} /></button>{open && <Modal title={success ? 'Your next move is underway.' : 'Let’s talk about this space.'} onClose={() => setOpen(false)}>{success ? <div className="text-center py-5"><span className="success-icon"><Check size={30} /></span><h3 className="text-xl font-semibold mt-5">Inquiry {isDemo ? 'saved to your preview' : 'sent'}</h3><p className="text-muted leading-7 mt-3 mb-6">{isDemo ? 'This is a demo inquiry. No message was sent to a real broker.' : 'You can follow this inquiry and your conversation from your workspace.'}</p><Link className="btn" to="/client/inquiries">View my inquiries <ArrowUpRight size={17} /></Link></div> : !user ? <div><p className="text-muted leading-7">Sign in to ask about {property.title} and keep your broker conversation in one place.</p><Link className="btn w-full mt-6" to={`/sign-in?next=${encodeURIComponent(location.pathname + '?inquire=1')}`}>Sign in to continue</Link></div> : user.role !== 'client' || !user.email_verified_at || user.status !== 'approved' ? <p role="alert" className="form-error">An approved client account with a verified email is required to send an inquiry.</p> : <form onSubmit={send}><p className="text-sm text-muted mb-5">Your message about <strong className="text-ink">{property.title}</strong> will be addressed to {property.broker?.name || 'the listing broker'}.</p><label className="field-label">Your message<textarea value={message} onChange={(event) => setMessage(event.target.value)} required minLength={10} maxLength={2000} rows={6} /></label><p className="text-right text-xs text-muted mt-2">{message.length} / 2,000</p>{error && <p role="alert" className="form-error">{error}</p>}<button className="btn w-full mt-5" disabled={sending}>{sending ? 'Sending…' : isDemo ? 'Submit demo inquiry' : 'Send inquiry'} <ArrowUpRight size={17} /></button><p className="flex gap-2 text-xs text-muted leading-5 mt-4"><LockKeyhole size={14} className="shrink-0" />{isDemo ? 'Preview only. Your message stays in this browser.' : 'Your inquiry is visible to you and the listing broker.'}</p></form>}</Modal>}</>
}
export function BrokerCard({ property, initialInquiry = false }: { property: Property; initialInquiry?: boolean }) {
  const broker = property.broker
  return <aside className="broker-card"><div className="pb-6 border-b border-line"><p className="eyebrow text-muted">{property.listing_type === 'lease' ? 'ASKING LEASE PRICE' : 'ASKING PRICE'}</p><p className="broker-price">{formatPrice(property)}</p><p className="text-xs text-muted mt-2">{property.listing_type === 'lease' && !property.price_period ? 'Confirm the rental period and terms with the broker.' : 'Contact the broker for complete terms.'}</p></div><p className="eyebrow text-muted mt-6 mb-4">YOUR LISTING PROFESSIONAL</p><div className="flex items-center gap-4"><div className="broker-avatar">{broker?.photo ? <PropertyImage src={broker.photo} alt={broker.name} className="w-full h-full object-cover" /> : <span>{broker?.name.slice(0, 1) || 'M'}</span>}</div><div><h2 className="font-semibold">{broker?.name || 'Listing broker'}</h2><p className="text-xs text-muted mt-1">{broker?.company || 'Property representative'}</p>{broker?.verified && <span className="flex gap-1 items-center mt-2 text-xs text-forest"><BadgeCheck size={13} /> Verified broker{isDemo ? ' · sample' : ''}</span>}</div></div><p className="text-sm text-muted leading-6 mt-5 mb-6">A direct conversation. A clearer picture of your next space.</p><InquiryButton property={property} initialOpen={initialInquiry} /><div className="mt-3"><SaveButton property={property} full /></div><p className="text-xs text-center text-muted mt-5">No obligation. Just possibilities.</p></aside>
}
